### ISSUE TITLE
copy only works for directly associated data

### ISSUE THREAD

**Issue by powtac** [jamienay/copyable_behavior#2]
When doing a saveAll() in __copyRecord() it only saves directly associated data and not a nested set of data with more directly associated data.

But there is already a Fix for 2.x by @Ceeram: https://github.com/ceeram/cakephp/compare/2.1...2.1-saveAllTheThings

**Comment by jamienay** [comment]
Great! I don't have time to maintain this right now so it's awesome to see community improvements. I haven't done a v2 project yet, but when I do I'll take a look.

**Comment by powtac** [comment]
There is already a 2.0 fork of your code: https://github.com/simkimsia/copyable_behavior

**Comment by jamienay** [comment]
This is a really late reply, but I am just about to commit a 2.0 version of this behavior that allows for deep copying.
